import { ExportPage } from '@/components/ExportPage'
import { Source } from '@/components/Source'
import { Notes } from '@/components/Notes'
import { findExport } from '@/components/exports'

const e = findExport('/providers/r2/')!

const USE = `import { createRegistry } from '@objectifthunes/ai-core'
import { createR2StorageProvider } from '@objectifthunes/provider-r2'

const registry = createRegistry()
registry.register(
  createR2StorageProvider({
    accountId: process.env.R2_ACCOUNT_ID,
    accessKeyId: process.env.R2_ACCESS_KEY_ID,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
    bucket: process.env.R2_BUCKET,
  }),
  { default: true },
)
//  capability: 'storage'   env: R2_ACCOUNT_ID · R2_ACCESS_KEY_ID · R2_SECRET_ACCESS_KEY · R2_BUCKET`

const SHAPE = `const port: StoragePort = {
  capability: 'storage',
  provider: 'r2',
  async put(input, ctx) {
    await s3.send(new PutObjectCommand({ Key: input.key, Body: input.bytes, ContentType: input.contentType }))
    return { url: \`\${publicBase}/\${input.key}\` }
  },
  async presign(key, expiresSec = 3600) {
    return getSignedUrl(s3, new GetObjectCommand({ Key: key }), { expiresIn: expiresSec })
  },
}`

export default async function Page() {
  return (
    <ExportPage group={e.group} title="provider-r2" lede={e.lede}>
      <p className="doc-p">
        A <code>StoragePort</code> over Cloudflare R2 — the sink most pipelines end on. It both writes
        (<code>put</code>) and signs (<code>presign</code>), so generated bytes land in a bucket and come back
        as a URL later steps can reference. Server-side; holds bucket credentials. Illustrative snippets only.
      </p>

      <Source code={USE} label="REGISTER · capability: storage · env: R2_*" />
      <Source code={SHAPE} lang="ts" label="THE PORT IT IMPLEMENTS" />

      <Notes>
        <p>
          Storage is special among the ports: its <code>url</code> output is meant to flow onward. A video step
          referencing <code>{'{{ steps.storeFrame.output.url }}'}</code> for its first frame, or an output map
          returning <code>{'{{ steps.store.output.url }}'}</code>, is the canonical shape — and exactly what the
          fake storage adapter mimics in the Studio.
        </p>
      </Notes>
    </ExportPage>
  )
}
