import { ExportPage } from '@/components/ExportPage'
import { Source } from '@/components/Source'
import { Notes } from '@/components/Notes'
import { findExport } from '@/components/exports'

const e = findExport('/ai-workflow/overview/')!

const SHAPE = `// A workflow is declarative JSON, validated by WorkflowSchema (Zod).
interface Workflow {
  id?: string
  description?: string
  inputs: Record<string, { type: 'string' | 'number' | 'boolean' | 'object' | 'array'; required: boolean; description?: string }>
  steps: Step[]
  output: Record<string, string>   // name → reference string
}
interface Step {
  id: string
  capability: 'text' | 'image' | 'video' | 'audio' | 'storage'
  provider?: string                 // omit to take the registry default
  model?: string
  params: Record<string, unknown>   // may contain {{ … }} references
  retry?: { attempts: number; baseDelayMs: number }
  costCap?: number
}`

const REFS = `{
  "description": "Kids' book page: illustration + narration",
  "inputs": { "page": { "type": "string", "required": true } },
  "steps": [
    { "id": "art",   "capability": "image", "params": { "prompt": "soft gouache: {{ inputs.page }}", "aspectRatio": "4:3" } },
    { "id": "voice", "capability": "audio", "params": { "kind": "speech", "prompt": "{{ inputs.page }}" } },
    { "id": "store", "capability": "storage",
      "params": { "key": "book/p1.png", "bytes": "{{ steps.art.output.bytes }}", "contentType": "{{ steps.art.output.contentType }}" } }
  ],
  "output": { "artUrl": "{{ steps.store.output.url }}" }
}`

export default async function Page() {
  return (
    <ExportPage group={e.group} title="ai-workflow" lede={e.lede}>
      <p className="doc-p">
        <code>@objectifthunes/ai-workflow</code> is the engine over the ai-core contract. A workflow is data —
        a Zod-validated JSON object of <code>inputs</code>, <code>steps</code> and <code>output</code> — so it
        can be authored by hand, generated by a model, stored in a database, or diffed in a PR. The package
        gives you four verbs over it: <code>validateWorkflow</code>, <code>runWorkflow</code>,{' '}
        <code>compileWorkflow</code>, and the <code>buildAuthoringPrompt</code> they share.
      </p>

      <Source code={SHAPE} lang="ts" label="WorkflowSchema" />

      <div>
        <h2 className="doc-h2">References</h2>
        <p className="doc-p">
          Params are templated. <code>{'{{ inputs.<name> }}'}</code> pulls a declared input;{' '}
          <code>{'{{ steps.<id>.output.<path> }}'}</code> pulls a previous step&apos;s output field. A string
          that is exactly one reference resolves to the raw value (so a <code>Uint8Array</code> of bytes flows
          intact); references embedded in a longer string are stringified in place.
        </p>
      </div>
      <Source code={REFS} lang="json" label="A WORKFLOW, END TO END" />

      <Notes>
        <p>
          Inputs and output both default to <code>{'{}'}</code>, so the smallest valid workflow is just a
          <code> steps</code> array. The reference grammar is the only “logic” a workflow has — there are no
          conditionals or loops, which is exactly what keeps validation total and runs deterministic.
        </p>
      </Notes>
    </ExportPage>
  )
}
